-- Migration 009: Organic Traffic Orchestrator tables

-- Content calendar (30-day plan generated by AI)
CREATE TABLE IF NOT EXISTS organic_calendar (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  topic       TEXT    NOT NULL,
  planned_for DATE    NOT NULL,
  status      TEXT    NOT NULL DEFAULT 'pending', -- pending | published | skipped
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Published content log
CREATE TABLE IF NOT EXISTS organic_logs (
  id          INTEGER  PRIMARY KEY AUTOINCREMENT,
  topic       TEXT     NOT NULL,
  article_title TEXT   NOT NULL,
  article_body  TEXT   NOT NULL,
  seo_title     TEXT   NOT NULL,
  seo_keywords  TEXT   NOT NULL, -- JSON array
  meta_description TEXT NOT NULL,
  social_posts  TEXT   NOT NULL, -- JSON array
  status      TEXT     NOT NULL DEFAULT 'published',
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Analytics per published content
CREATE TABLE IF NOT EXISTS organic_analytics (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  log_id      INTEGER NOT NULL REFERENCES organic_logs(id),
  views       INTEGER DEFAULT 0,
  clicks      INTEGER DEFAULT 0,
  conversions INTEGER DEFAULT 0,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
